sudo: required
services:
  - docker
env:
  global:
    # Get the current SHA from git. Used in deploy.sh
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # Decryptera
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # Installera CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # Sätt Environment
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Installera kubectl
  - gcloud components update kubectl
  # Aktivera service account
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-234115
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mrfredland/react-test-v2 -f ./client/Dockerfile.dev ./client

script:
  - docker run mrfredland/react-test-v2 npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
