
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssues
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'info@metricio.se'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
